export const requestBoardData = [
    {
        id: "1",
        name: "varun",
        skill: "useEffect",
        color: "green",
        votes: [
            {
                name: "Prakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Manish",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Yash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
        ],
    },
    {
        id: "2",
        name: "Yasj Raj",
        skill: "useState",
        color: "blue",
        votes: [
            {
                name: "Samarth",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Rahul",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Pankaj",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Prasidh",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Virat",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Prakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
        ],
    },
    {
        id: "3",
        name: "Manish",
        skill: "java",
        color: "blue",
        votes: [
            {
                name: "Virat",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Prachi",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Akriti",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Prakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
        ],
    },
    {
        id: "4",
        name: "Ankush Dharkar",
        skill: "rust",
        color: "yellow",
        votes: [
            {
                name: "Anushka",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Simran",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Alia",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Prakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Prakah",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Pakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
        ],
    },
    {
        id: "5",
        name: "Bhavika",
        skill: "react",
        color: "green",
        votes: [
            {
                name: "Preeti",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Bhavika",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Kanchan",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Prakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Arakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Mrakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Poakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
        ],
    },
    {
        id: "6",
        name: "Sunny",
        skill: "firebase",
        color: "blue",
        votes: [
            {
                name: "Prakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Praash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Praakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "APrakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "LPrakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
            {
                name: "Drakash",
                img: "",
                date: "16/07/2022",
                reason: "Lorem ipsum dolor sit amet consectetur. Lacus consequat non porttitor faucibus. Mattis nec felis sagittis justo id volutpat. Et ut non semper quam a consectetur erat. Eget eu in diam semper eu sit dui id.",
            },
        ],
    },
];
